name: GitHub Actions Deploy
run-name: ${{ github.actor }} is has pushed and the repo will be deployed
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: make .ssh folder
        run: mkdir ~/.ssh
      - name: Add known hosts file
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          known_hosts: ${{ secrets.REMOTE_HOST_FINGERPRINT }}
      - name: remote execute git pull
        run: ssh ${{ secrets.REMOTE_HOST_USER }}@${{ secrets.REMOTE_HOSTNAME }} 'cd `ls` && git pull origin main'
        