name: GitHub Actions Deploy
run-name: ${{ github.actor }} has pushed and the repo will be deployed to the server
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: make .ssh folder
        run: mkdir ~/.ssh
      - name: Add known hosts file
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          known_hosts: ${{ secrets.REMOTE_KNOWN_HOSTS }}
      - name: change into repo folder, pull code, run envoy tasks
        run: "ssh ${{ secrets.REMOTE_APP_USERNAME}}@${{ secrets.REMOTE_HOSTNAME }} 'cd `ls` && php vendor/bin/envoy run deploy --host={{ secrets.REMOTE_HOSTNAME }}'"